version: "3"
services:
  smp_psql:
    image: "postgres:13.6-alpine"
    container_name: "smp_db"
    environment:
      - POSTGRES_USER=smp
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=smp
    ports:
      - "54320:5432"
  redis:
    image: "redis:7.0.2-alpine"
    container_name: "smp_redis"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"